#!/usr/bin/env python
import os
import daemon
import optparse

import tornado.web
import tornado.ioloop
import tornado.httpserver

def main(opts, args):
    import blog
    import blog.handlers
    application = tornado.web.Application(
        blog.handlers.paths,
        login_url='/login',
        cookie_secret='3c8670ee7fbfea1757c7c25ae0bb1dd2',
        template_path=os.path.join(blog.base_path, 'templates'),
        static_path=os.path.join(blog.base_path, 'static'),
        xsrf_cookies=True,
        debug=opts.debug)
    http_server = tornado.httpserver.HTTPServer(application)
    http_server.listen(opts.port)
    tornado.ioloop.IOLoop.instance().start()

if __name__ == '__main__':
    parser = optparse.OptionParser()
    parser.add_option('-d', dest='debug', action='store_true', default=False, help='run in debug mode')
    parser.add_option('-f', dest='foreground', action='store_true', default=False, help='run in the foreground')
    parser.add_option('-p', '--port', type='int', default='8888', help='which port to listen on')
    opts, args = parser.parse_args()

    if opts.debug:
        opts.foreground = True

    if opts.foreground:
        main(opts, args)
    else:
        with daemon.DaemonContext():
            main(opts,args)
